HC200ok/vue3-easy-data-table

src/components/DataTable.vue, src/mock.ts, src/modes/Client.vue, test/DataTable.spec.js
Add unit tests by using vitest
=> Add unit tests

package.json, src/components/DataTable.vue
=> fix: remove props.item watch

package.json, src/components/DataTable.vue
=> Fix: support nested sorting

package.json, src/App.vue, src/components/DataTable.vue, src/modes/Client.vue, src/modes/ServerSide.vue, src/types/main.d.ts, types/main.d.ts
=> feature: add column width and fixed columns

package.json, src/components/DataTable.vue, src/modes/Client.vue
=> fix:fixed-column-bug-in-safari

package.json, src/components/DataTable.vue
=> update show-footer prop to hide-footer

package.json, src/components/DataTable.vue, src/modes/Client.vue
=> fix table hover color

package.json, src/components/DataTable.vue, src/mock.ts, src/modes/Client.vue
=> fix empty background color

package.json, src/components/DataTable.vue, src/modes/Client.vue
=> Fix: single field sorting duplicate rows

package.json, src/index.ts, src/types/index.d.ts
=> Support cdn

package.json, src/components/DataTable.vue
=> feature: add header slot

package.json, src/components/DataTable.vue
=> optimize header sort click area

package.json, src/components/DataTable.vue, src/components/LoadingLine.vue, src/mock.ts
=> async data for expand row

package.json, src/components/DataTable.vue
=> fix even-row default color

package.json, src/components/ButtonsPagination.vue
=> optimize buttons pagination active border

package.json, src/components/DataTable.vue
=> fix server side last index

.eslintrc.js, package.json, src/App.vue, src/components/ButtonsPagination.vue, src/components/DataTable.vue, src/components/MutipleSelectCheckBox.vue, src/components/SingleSelectCheckBox.vue, src/hooks/useClickRow.ts, src/hooks/useExpandableRow.ts, src/hooks/useFixedColumn.ts, src/hooks/useHeaders.ts, src/hooks/usePageItems.ts, src/hooks/usePagination.ts, src/hooks/useRows.ts, src/hooks/useServerOptions.ts, src/hooks/useTotalItems.ts, src/mock.ts, src/modes/Client.vue, src/modes/ServerSide.vue, src/scss/checbox.scss, src/scss/vue3-easy-data-table.scss, src/types/internal.d.ts, src/types/main.d.ts, src/utils.ts, types/main.d.ts
=> refactory: use hooks

package.json, src/components/DataTable.vue, src/scss/vue3-easy-data-table.scss
=> fix fixed-height

src/components/DataTable.vue, src/hooks/usePageItems.ts, src/hooks/useRows.ts
=> rename rowsPerPageReactive to rowsPerPageRef

package.json, src/components/DataTable.vue, src/modes/Client.vue, src/types/main.d.ts, src/withOptionalProps.ts, types/main.d.ts
=> Optimize: extract props from dataTable component

package.json, src/App.vue, src/components/DataTable.vue, src/hooks/useExpandableRow.ts, src/modes/Client.vue, src/modes/ExpandLoading.vue, src/modes/ServerSide.vue
=> fix expand row after pageItems updates

package-lock.json, package.json, src/components/DataTable.vue, src/hooks/useRows.ts, src/modes/Client.vue
=> Customize rows per page

package.json, src/components/DataTable.vue, src/modes/Client.vue, src/propsWithDefault.ts, src/scss/checbox.scss, src/scss/vue3-easy-data-table.scss, src/types/main.d.ts, types/main.d.ts
=> New props/text direction

package.json, src/components/DataTable.vue, src/propsWithDefault.ts, src/scss/vue3-easy-data-table.scss
=> feature: add new prop table-min-height

package.json, src/components/DataTable.vue, src/modes/ExpandLoading.vue
=> fix: async expand with select items

package.json, src/App.vue, src/components/DataTable.vue, src/hooks/usePagination.ts, src/mock.ts, src/modes/Client.vue, src/propsWithDefault.ts, src/utils.ts
=> bump to 1.4.18

package.json, src/App.vue, src/components/DataTable.vue, src/hooks/useExpandableRow.ts, src/modes/Client.vue, src/modes/ExpandLoading.vue, src/modes/ServerSide.vue
=> fix: back to 1st page when using async expanding

package.json, src/hooks/useTotalItems.ts, src/modes/Client.vue
=> fix filtering nested bug

package-lock.json, package.json, src/App.vue, src/components/DataTable.vue, src/hooks/useHeaders.ts, src/hooks/useServerOptions.ts, src/hooks/useTotalItems.ts, src/modes/Client.vue, src/modes/ServerSide.vue, src/propsWithDefault.ts, src/scss/vue3-easy-data-table.scss, src/types/internal.d.ts, src/types/main.d.ts, types/main.d.ts
=> add feature: multi sort

package.json, src/components/DataTable.vue, src/modes/Client.vue
=> fix: cdn mode slot camelCase error

package.json, src/hooks/useTotalItems.ts, src/modes/Client.vue, src/propsWithDefault.ts
=> feature: search across multiple columns

package.json, src/components/DataTable.vue, src/hooks/useTotalItems.ts, src/modes/Client.vue
=> fix: nested field search & body-slot

package.json, src/components/DataTable.vue, src/hooks/useClickRow.ts, src/modes/Client.vue, src/propsWithDefault.ts, src/types/internal.d.ts
=> add double click event

package.json, src/components/DataTable.vue, src/modes/Client.vue, src/propsWithDefault.ts
=> add prop click-row-to-expand

package.json, src/components/DataTable.vue, src/hooks/useTotalItems.ts, src/modes/Client.vue, src/types/internal.d.ts
=> add selectRow event

package.json, src/components/DataTable.vue, src/hooks/useTotalItems.ts, src/modes/Client.vue, src/types/internal.d.ts
=> add deselect-row event

package.json, src/App.vue, src/components/DataTable.vue, src/modes/Client.vue
https://github.com/HC200ok/vue3-easy-data-table/issues/181
=> fix filter pagination

package.json, src/components/DataTable.vue, src/modes/Client.vue
=> fix the second param of bodyItemClassName function

package.json, src/components/DataTable.vue, src/types/main.d.ts, types/main.d.ts
=> use rowNumber/columnNumber instead of index

package.json, src/components/DataTable.vue, src/modes/Client.vue, src/propsWithDefault.ts
=> add tableNodeId prop

package.json, src/components/DataTable.vue, src/modes/Client.vue, src/types/internal.d.ts
=> add updatePageItems event

package.json, src/components/DataTable.vue, src/hooks/useHeaders.ts, src/modes/Client.vue, src/propsWithDefault.ts, src/types/internal.d.ts
=> add updateTotalItems event

package.json, src/components/DataTable.vue, src/modes/Client.vue
Allows a slot header to be defined for all columns.
- [ x] Feature
=> add generic header slot

src/types/main.d.ts, types/main.d.ts
I missed the types/main.d.ts in my PR #224 - sorry!
=> Fix types for comparsion options in types/main.d.ts

package.json, src/components/DataTable.vue, src/modes/Client.vue
incorporate a generic slot for item
=> add generic item slot

src/propsWithDefault.ts
Change parameter from deault to default
- [ x] Fix
- [ x] Title as described
=> Fix typo in table props

package-lock.json, package.json
this fixes [CVE-2022-35204](https://devhub.checkmarx.com/cve-details/CVE-2022-35204/)
=> chore(deps): update vite to non-vulnerable version
